{{- range $job_name, $job_options := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadtest-bbb-{{ $job_name }}
  namespace: loadtest
spec:
  schedule: {{ $job_options.schedule | quote }}
  suspend: true
  jobTemplate:
    spec:
      completions: {{ $job_options.jobsParallelism }}
      parallelism: {{ $job_options.jobsParallelism }}
      template:
        metadata:
          labels:
            app: loadtest-bbb
            test: loadtest-{{ $job_options.serviceName }}
            pod: {{ $job_name }}
        spec:
          containers:
          - name: {{ $job_name }}
            image: {{ $job_options.image }}
            imagePullPolicy: Always
            resources:
              requests:
                memory: "1100Mi"
                cpu: "0.5"
              limits:
                memory: "1100Mi"
                cpu: "1.5"
            ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
            args:
              ['./loadtest/tests/{{ $job_options.scriptPath }}']
            env:
              - name: BRANCH
                value: {{ $.Values.branch }}
              - name: BIGBLUEBOT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: bbb-secret
                    key: userSecret
              - name: BIGBLUEBOT_HOST
                value: {{ $.Values.host }}
              - name: BIGBLUEBOT_FETCH_HOST
                value: {{ $.Values.fetchHost }}
              - name: BIGBLUEBOT_VERSION
                value: {{ $job_options.bbbVersion | quote }}
              - name: BIGBLUEBOT_ROOM
                valueFrom:
                  secretKeyRef:
                    name: bbb-secret
                    key: roomSecret
              - name: BIGBLUEBOT_BOTS
                value: {{ $job_options.bbbBots | quote }}
              - name: BIGBLUEBOT_WAIT
                value: {{ $job_options.botJoinGaps | quote }}
              - name: BIGBLUEBOT_LIFE
                value: {{ $job_options.botLifeDuration | quote }}
          restartPolicy: OnFailure
---
{{- end }}