{{- range $job_name, $job_options := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadtest-bbb-{{ $job_name }}
  namespace: loadtest
spec:
  schedule: {{ $job_options.schedule | quote }}
  suspend: true
  jobTemplate:
    spec:
      completions: {{ $job_options.jobsParallelism }}
      parallelism: {{ $job_options.jobsParallelism }}
      template:
        metadata:
          labels:
            test: loadtest-{{ $job_options.serviceName }}
            pod: {{ $job_name }}
        spec:
          #volumes:
          #- name: configmap
            #configMap:
              #name: configmap-chat
          containers:
          - name: {{ $job_name }}
            image: {{ $job_options.image }}
            imagePullPolicy: Always
            #volumeMounts:
            #- #name: configmap
              #mountPath: /bot-script
            args:
              ['./loadtest/tests/{{ $job_options.scriptPath }}']
            env:
              - name: BRANCH
                value: DBP-193-Extend-BBB-loadtest-with-Audio-and-Video
              - name: BBB_SECRET
                valueFrom:
                  secretKeyRef:
                    name: bbb-secret
                    key: userSecret
              - name: BIGBLUEBOT_HOST
                value: {{ $job_options.host }}
              - name: BIGBLUEBOT_FETCH_HOST
                value: {{ $job_options.fetchHost }}
              - name: BIGBLUEBOT_VERSION
                value: {{ $job_options.bbbVersion | quote }}
              - name: BBB_ROOM
                valueFrom:
                  secretKeyRef:
                    name: bbb-secret
                    key: roomSecret
              - name: BIGBLUEBOT_BOTS
                value: {{ $job_options.bbbBots | quote }}
              - name: BIGBLUEBOT_WAIT
                value: {{ $job_options.botLifeDuration | quote }}
              - name: BIGBLUEBOT_LIFE
                value: {{ $job_options.botJoinGaps | quote }}
          restartPolicy: OnFailure
---
{{- end}}