apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: loadtest-bbb
spec:
  selector:
    matchLabels:
      app: loadtest-bbb
  podMetricsEndpoints:
  - port: metrics
    interval: 5s