branch: DBP-195-Extend-BBB-loadtest-with-Audio-and-Video
host: https://bbb.dbpinfra.dp.dbildungsvk.de
fetchHost: https://bbb-3.bbb.dbpinfra.dp.dbildungsvk.de/
cronjobs:
  chat-scenario:
    scriptPath: "chat-test.js"
    schedule: "* * * * *"
    jobsParallelism: 5
    serviceName: chat-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest:1.0.0
    bbbVersion: 2.6
    bbbBots: "10"
    botLifeDuration: "3600000"
    botJoinGaps: "3000"
  audio-scenario:
    scriptPath: "audio-test.js"
    schedule: "* * * * *"
    jobsParallelism: 151
    serviceName: audio-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest:1.0.0
    bbbVersion: 2.6
    bbbBots: 1
    botLifeDuration: "3600000"
    botJoinGaps: "3000"
  microphone-scenario:
    scriptPath: "microphone-test.js"
    schedule: "* * * * *"
    jobsParallelism: 4
    serviceName: microphone-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest:1.0.0
    bbbVersion: 2.6
    bbbBots: "1"
    botLifeDuration: "3600000"
    botJoinGaps: "3000"
  video-scenario:
    scriptPath: "video-test.js"
    schedule: "* * * * *"
    jobsParallelism: 71
    serviceName: video-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest:1.0.0
    bbbVersion: 2.6
    bbbBots: "1"
    botLifeDuration: "3600000"
    botJoinGaps: "3000"