cronjobs:
  chat-scenario:
    scriptPath: "bot-script/chat-test.js"
    schedule: "10 * * * *"
    jobsParallelism: 1
    serviceName: chat-scenario
    image: sad-dell:1.1.1
    host: "https://bbb.dbpinfra.dp.dbildungsvk.de"
    fetchHost: "https://bbb-3.bbb.dbpinfra.dp.dbildungsvk.de/"
    bbbVersion: 2.6
    bbbBots: 1
    botLifeDuration: 20000
    botJoinGaps: 10000