cronjobs:
  chat-scenario:
    scriptPath: chat-test.js
    schedule: 0 8 * * *
    jobsParallelism: 1
    serviceName: chat-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest:latest #TODO image not working
    host: "https://bbb.dbpinfra.dp.dbildungsvk.de"
    fetchHost: "https://bbb-3.bbb.dbpinfra.dp.dbildungsvk.de/"
    bbbVersion: "2.6"
    bbbBots: 1
    botLifeDuration: 60000 #in ms
    botJoinGaps: 2000 #in ms