cronjobs:
  chat-scenario:
    scriptPath: "chat-test.js"
    schedule: "10 * * * *"
    jobsParallelism: 1
    serviceName: chat-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest:latest
    host: https://bbb.dbpinfra.dp.dbildungsvk.de
    fetchHost: https://bbb-3.bbb.dbpinfra.dp.dbildungsvk.de/
    bbbVersion: 2.6
    bbbBots: 1
    botLifeDuration: 60000
    botJoinGaps: 5000
  audio-scenario:
    scriptPath: "audio-test.js"
    schedule: "10 * * * *"
    jobsParallelism: 1
    serviceName: chat-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest:latest
    host: https://bbb.dbpinfra.dp.dbildungsvk.de
    fetchHost: https://bbb-3.bbb.dbpinfra.dp.dbildungsvk.de/
    bbbVersion: 2.6
    bbbBots: 1
    botLifeDuration: 60000
    botJoinGaps: 5000