cronjobs:
  chat-scenario:
    scriptPath: "chat-test.js"
    schedule: "* * * * *"
    jobsParallelism: 1
    serviceName: chat-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest-1.0.0
    host: 
    fetchHost:
    bbbVersion: 2.6
    bbbBots: 10
    botLifeDuration: 60000
    botJoinGaps: 2000
  audio-scenario:
    scriptPath: "audio-test.js"
    schedule: "* * * * *"
    jobsParallelism: 1
    serviceName: audio-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest-1.0.0
    host: 
    fetchHost:
    bbbVersion: 2.6
    bbbBots: 10
    botLifeDuration: 60000
    botJoinGaps: 2000
  microphone-scenario:
    scriptPath: "microphone-test.js"
    schedule: "* * * * *"
    jobParallelism: 1
    serviceName: microphone-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest-1.0.0
    host: 
    fetchHost:
    bbbVersion: 2.6
    bbbBots: 5
    botLifeDuration: 60000
    botJoinGaps: 2000
  video-scenario:
    scriptPath: "video-test.js"
    schedule: "* * * * *"
    jobParallelism: 1
    serviceName: video-scenario
    image: ghcr.io/dbildungsplattform/bbb-loadtest-1.0.0
    host: 
    fetchHost: 
    bbbVersion: 2.6
    bbbBots: 2
    botLifeDuration: 60000
    botJoinGaps: 7000
  
